# Notebook configuration file ============================================================
# 
# This file contained options controlling notebook behavior and is meant to be customized
# by the user. 
#
#
# Website building options ---------------------------------------------------------------
#
# The bootstrap theme used in the website. For current options, see:
# "http://rmarkdown.rstudio.com/html_document_format.html#appearance-and-style"
# At the time of writing, valid options are:
# "default", "cerulean", "journal", "flatly", "readable", "spacelab", "united", "cosmo"
website_theme: journal
#
# Whether intermediate files made during the building of the website should be removed.
# "yes" and "no" are valid options.
clean_website: yes
#
# Whether to apply the bootstrap theme specified by the "website_theme"
# configuration option to note content.
# "yes" and "no" are valid options.
theme_note_content: yes
